#===============================================
#   - name: Setup Debug Session
#     uses: csexton/debugger-action@master
#===============================================

name: AAAAAAAAAAAAA

on:
  #release:
  #  types: published
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        url: [https://github.com/breakings/OpenWrt, https://github.com/ophub/kernel, https://github.com/Tao173/Auto-Update-Router]
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 ${{ matrix.url }
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"
    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: ${{ matrix.url }



