#===============================================
#   - name: Setup Debug Session
#     uses: csexton/debugger-action@master
#===============================================

name: published

on:
  #release:
  #  types: published
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Commit
      run: |
        git config --global --add safe.directory '*'     
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: Tao173/ESP-HA
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }} 
        path: my-tools      
    - name: Setup Debug Session  
      uses: csexton/debugger-action@master


