name: Delete Artifacts Update Checker

on:
  #release:
  #  types: published
  repository_dispatch:
    types: [immortalwrt Source Code Update]  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main        
    - name: Setup Debug Session 'touch /tmp/keepalivegit'
      uses: csexton/debugger-action@master
